[workspace]

members = ["aoc_day_01", 
    "aoc_day_02", 
    "aoc_day_03", 
    "aoc_day_04", 
    "aoc_day_05", 
    "aoc_day_06", 
    "aoc_day_07", 
    "aoc_day_08", 
    "aoc_day_09", 
    "aoc_day_10",
    "aoc_day_11",
    "aoc_day_12",
    "aoc_day_13",
    "aoc_day_14",
    "aoc_day_15",
    "aoc_day_16",
    "aoc_day_17",
    "aoc_day_18",
    "aoc_day_19",
    "aoc_day_20",
    "aoc_day_21",
    "aoc_day_22",
    "aoc_day_23"]