[package]
name = "aoc_day_11"
version = "0.1.0"
authors = ["Christiaan Hartman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
